### PR TITLE
enable language selection...

### PR DESCRIPTION
**Pull request by denesnori**
I made a drop down menu for language selection. 
Now I'm working on the non-ASCII character issue.

### CODE REVIEW

**Comment by emilyb7** [comment]
@denesnori I'm getting an error when I try to run this! Don't know if it's just me?

**Comment by denesnori** [comment]
What kind of error do you get?

**Comment by denesnori** [comment]
It works for me fine

**Comment by denesnori** [comment]
Hups...I remember something...Initially I mispelled the name of the new English dictionary file. So there was a point when all the languages worked but English...But I fixed this in one of the later commits.

**Comment by emilyb7** [comment]
From my terminal...

```
[nodemon] starting `node server.js`
Server running at port 8000
/Users/emilybertwistle/FAC/backend-badgers-autocomplete/src/search.js:23
      words = data.split('\n');
                  ^

TypeError: Cannot read property 'split' of undefined
    at ReadFileContext.callback (/Users/emilybertwistle/FAC/backend-badgers-autocomplete/src/search.js:23:19)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by emilyb7** [comment]
YAY now it's working !

**Comment by denesnori** [comment]
Yes! You got this because I misspelled the name of the English dictionary file....So the response was undefined...and you can't split on an undefined. 

Please pull the latest updates..and it should work! :)

**Comment by denesnori** [comment]
:)

**Pull request merged**
